name: 'Ëá™ÂÆö‰πâshellÊûÑÂª∫Âπ∂‰∏ãËΩΩ'

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      SETTING_SHELL_URL:
        description: 'ËÆæÁΩÆÊûÑÂª∫ÁéØÂ¢ÉÁöÑshellÂú∞ÂùÄ'
        required: false
      GIT_REPO_URL:
        description: 'git‰ªìÂ∫ìÂú∞ÂùÄ'
        required: false
      GIT_REPO_BRANCH:
        description: 'git‰ªìÂ∫ìÂàÜÊîØ'
        required: false
      BUILD_BEFORE_SHELL_URL:
        description: 'ÊûÑÂª∫ÂâçshellÂú∞ÂùÄ'
        required: false
      BUILD_SHELL_URL:
        description: 'ÊûÑÂª∫shellÂëΩ‰ª§Âú∞ÂùÄ'
        required: true
      BUILD_AFTER_SHELL_URL:
        description: 'ÊûÑÂª∫ÂêéshellÂëΩ‰ª§Âú∞ÂùÄ'
        required: false
      BUILD_TARGET_PATH:
        description: 'ÊûÑÂª∫‰∫ßÁâ©Ë∑ØÂæÑ'
        required: true
        default: './dist/*'
      UPLOAD_RELEASE:
        description: 'ÊòØÂê¶‰∏ä‰º†Âà∞RELEASEÈ°µÈù¢'
        required: false
        default: 'false'
        type: boolean
      UPLOAD_TRANSFER:
        description: '‰∏ä‰º†ÊúçÂä°,Â¶Çwet,ËßÅgithub.com/Mikubill/transfer#support'
        required: false
      UPLOAD_TAG:
        description: '‰∏ä‰º†Êñá‰ª∂Áî®ÁöÑTAG,ÈªòËÆ§‰ΩøÁî®ÊûÑÂª∫Êó∂Èó¥'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      # ‰∫ßÁîütag
      - name: Generate tag
        id: tag
        run: |
          tag=build-customize_$(date +'%m-%d_%H-%M-%S')
          [ ! "${{github.event.inputs.UPLOAD_TAG}}" = "" ] && tag=${{github.event.inputs.UPLOAD_TAG}}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      # ÂºÄÂßãÊûÑÂª∫
      - name: Build
        id: build
        run: |
          rm -rf /tmp/dist
          mkdir -p /tmp/dist
          echo -e "github actions build\nstart time: $(date +'%Y-%m-%d %H:%M:%S')\n" > release.txt
          start=$(date +%s)
          if [[ "${{ github.event.inputs.SETTING_SHELL_URL }}" ]] ;then wget "${{github.event.inputs.SETTING_SHELL_URL}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh | tee /tmp/build_log/setting.log; fi
          if [[ "${{ github.event.inputs.GIT_REPO_URL }}" ]] && if [[ "${{ github.event.inputs.GIT_REPO_BRANCH }}" ]] ;then git clone --depth 1 -b "${{ github.event.inputs.GIT_REPO_BRANCH }}" "${{github.event.inputs.GIT_REPO_URL}}" . ; else git clone --depth 1 "${{github.event.inputs.GIT_REPO_URL}}" . ; fi
          if [[ "${{ github.event.inputs.BUILD_BEFORE_SHELL_URL }}" ]] ;then wget "${{github.event.inputs.SETTING_SHELL_URL}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh | tee /tmp/build_log/before.log; fi
          wget "${{github.event.inputs.SETTING_SHELL_URL}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh | tee /tmp/build_log/build.log
          if [[ "${{ github.event.inputs.BUILD_AFTER_SHELL_URL }}" ]] ;then wget "${{github.event.inputs.SETTING_SHELL_URL}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh | tee /tmp/build_log/after.log; fi
          end=$(date +%s)
          take=$(( end - start ))
          echo "end time: $(date +'%Y-%m-%d %H:%M:%S')" >> release.txt
          echo "build use ${take}s" >> release.txt
          cp -r ${{ github.event.inputs.BUILD_TARGET_PATH }} /tmp/dist
          tar -zcvf /tmp/dist.tar.gz -C /tmp/dist $(ls /tmp/dist) > /dev/null

      # ‰∏ä‰º†ÊûÑÂª∫Êó•Âøó
      - name: Upload build logs
        uses: actions/upload-artifact@main
        with:
          name: log_${{ steps.tag.outputs.tag }}
          path: /tmp/build_log
          retention-days: 1

      # ‰∏ä‰º†ÊûÑÂª∫‰∫ßÁâ©
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.tag.outputs.tag }}
          path: /tmp/dist.tar.gz
          retention-days: 1

      # ‰∏ä‰º†Âà∞‰∏≠ËΩ¨ÊúçÂä°
      - name: Upload firmware to transfer
        if: github.event.inputs.UPLOAD_TRANSFER && !failure() && !cancelled()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer ${{ github.event.inputs.UPLOAD_TRANSFER }} --no-progress /tmp/dist.tar.gz 2>&1 | tee transfer.log
          url=$(cat transfer.log | grep https | cut -f3 -d" ")
          echo "üîó External Download Link: $url" >> release.txt
          echo "::warning ::External Download Link: $url"

      # ÁîüÊàêrelease
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: github.event.inputs.UPLOAD_RELEASE == 'true' && !failure() && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          body_path: release.txt
          files: /tmp/dist.tar.gz
